services:
  fudosan-checker:
    build: .
    container_name: fudosan-checker
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
    environment:
      - TZ=Asia/Tokyo
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1492114840720773140/l2SWZeiUbOSf8Hvq9Qz8kyoxYUW93kUrdctrn3KH-c23ibiYrFIzozTmVObnqXu4Z31w
